apiVersion: v1
stringData:
  endpoint: {{ .Release.Name }}-master.{{ .Release.Namespace }}.svc
  port: "9200"
  username: "elastic"
  {{- if .Values.encodePassword }}
  password: "{{ (b64dec .Values.encodePassword) | default .Values.elasticPassword }}"
  {{- else }}
  password: "{{ .Values.elasticPassword }}"
  {{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-credential
  namespace: {{ .Release.Namespace }}
type: Opaque