apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: elasticsearch-serviceaccount
spec:
  template: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ .Globe.Name }}-job