middlewareDefinition: elasticsearch-cluster-active
values:
  - name: elasticsearch
    path: spec|configurations|elasticsearch-es-config|values|args
    parameters:
      - thread_pool.write.queue_size:
          - name: default
            value: 10000
          - name: isReboot
            value: y
          - name: range
            value: [1-31536000]
          - name: describe
            value: "通过自定义queue大小，调整文档写入的队列大小"
      - thread_pool.search.queue_size:
          - name: default
            value: 1000
          - name: isReboot
            value: y
          - name: range
            value: [1-31536000]
          - name: describe
            value: "通过自定义queue大小，调整搜索的队列大小"
      - xpack.watcher.enabled:
          - name: default
            value: false
          - name: isReboot
            value: y
          - name: range
            value: [true|false]
          - name: describe
            value: "开启后，可使用X-Pack的Watcher功能"
      - gateway.expected_data_nodes:
          - name: default
            value: 0
          - name: isReboot
            value: y
          - name: range
            value: [0-100000]
          - name: describe
            value: "Number of data nodes expected in the cluster. Recovery of local shards begins when the expected number of data nodes join the cluster. Defaults to 0."
      - gateway.recover_after_data_nodes:
          - name: default
            value: 0
          - name: isReboot
            value: y
          - name: range
            value: [0-100000]
          - name: describe
            value: "Recover as long as this many data nodes have joined the cluster."
      - http.cors.allow-headers:
          - name: default
            value: Authorization
          - name: isReboot
            value: y
          - name: range
            value: [X-Requested-With|Content-Type|Content-Length|Authorization|Accept|User-Agent|X-Elastic-Client-Meta]
          - name: describe
            value: "The header information for setting cross-origin allowance."
      - http.cors.allow-credentials:
          - name: default
            value: false
          - name: isReboot
            value: y
          - name: range
            value: [true|false]
          - name: describe
            value: "Whether the Access-Control-Allow-Credentials header should be returned. Defaults to false."
      - bootstrap.memory_lock:
          - name: default
            value: false
          - name: isReboot
            value: y
          - name: range
            value: [true|false]
          - name: describe
            value: "To disable swap at the database level, while also setting the session parameter memlock to unlimited."
      - action.auto_create_index:
          - name: default
            value: "true"
          - name: isReboot
            value: y
          - name: range
            value: [true|false]
          - name: describe
            value: "Automatically create an index if it doesn’t already exist and apply any configured index templates. Defaults to true."