baselineName:
  - name: "Cluster Mode"
    name-zh: "集群模式"
  - name: "Cluster Mode A-A"
    name-zh: "集群模式-双活"
  - name: "Mixed Mode"
    name-zh: "混合模式"
  - name: "Mixed Mode A-A"
    name-zh: "混合模式-双活"

  - name: "Standard"
    name-zh: "标准版"
  - name: "HighAvailability"
    name-zh: "高可用版"
description:
  - name: "Elasticsearch Database"
    name-zh: "Elasticsearch 数据库"

  - name: "Cluster Mode Baseline, incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "集群模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
  - name: "Mixed Mode Baseline, incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "混合模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."

  - name: "High Availability/HA Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "高可用版基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."

  - name: "Standard Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "标准版基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."




  - name: "Please enter a custom quota, the unit is `Core`"
    name-zh: "请输入自定义配额,单位为Core"
  - name: "Please enter a custom quota, the unit is `Gi`"
    name-zh: "请输入自定义配额,单位为Gi"
  - name: "Nodes,It is recommended to have at least 3 to ensure high availability."
    name-zh: "节点数量，建议至少3个以保证高可用"
  - name: "Number of nodes, please enter an odd number greater than or equal to 3"
    name-zh: "节点数量，请输入3或3以上的奇数"

  - name: "Please enter the storage size"
    name-zh: "请输入存储大小"
  - name: "Please select storage"
    name-zh: "请选择存储"
  - name: "Please enter a password consisting of English letters, numbers, or the special characters \"~, _, .\""
    name-zh: "请输入由英文字母、数字或特殊字符“~、_、.”组成的密码信息"
  - name: "Please enter a valid port number"
    name-zh: "请输入合法端口号"
  - name: "Minimum storage size is 1"
    name-zh: "存储大小最低为1"

  - name: "The minimum value for client count is 1"
    name-zh: "client节点数量，至少为1"
  - name: "The minimum value for Coordinator count is 1"
    name-zh: "Coordinator 节点数量，至少为1"
  - name: "The minimum value for kibana count is 1"
    name-zh: "kibana节点数量，至少为1"
  - name: "The minimum value for master count is 3"
    name-zh: "master节点数量，至少为3"
  - name: "The minimum value for data count is 3"
    name-zh: "data节点数量，至少为3"

  - name: "Number of master nodes, please enter an odd number greater than or equal to 3"
    name-zh: "master节点数量，请输入3或3以上的奇数"
  - name: "Number of cold nodes, please enter an even number greater than or equal to 2"
    name-zh: "cold节点数量，请输入2或2以上的偶数"
  - name: "Number of data nodes, please enter an even number greater than or equal to 4"
    name-zh: "data节点数量，请输入4或4以上的偶数"

  - name: "Through custom queue size, adjust the queue size for document writing"
    name-zh: "通过自定义queue大小，调整文档写入的队列大小"
  - name: "Through custom queue size, adjust the queue size for search"
    name-zh: "通过自定义queue大小，调整搜索的队列大小"
  - name: "When enabled, the Watcher feature of X-Pack can be used"
    name-zh: "开启后，可使用X-Pack的Watcher功能"
  - name: "Number of data nodes expected in the cluster. Recovery of local shards begins when the expected number of data nodes join the cluster. Defaults to 0."
    name-zh: "集群中预期的数据节点数量。当预期数量的数据节点加入集群后，本地分片的恢复将开始。默认为0。"
  - name: "Recover as long as this many data nodes have joined the cluster."
    name-zh: "只要有这么多数据节点加入集群，就开始进行分片恢复。"
  - name: "The header information for setting cross-origin allowance."
    name-zh: "设置跨域允许的请求头信息。"
  - name: "Whether the Access-Control-Allow-Credentials header should be returned. Defaults to false."
    name-zh: "是否应返回Access-Control-Allow-Credentials响应头。默认为false。"
  - name: "To disable swap at the database level, while also setting the session parameter memlock to unlimited."
    name-zh: "在数据库层面禁用交换分区，同时将会话参数memlock设置为无限制。"
  - name: "Automatically create an index if it doesn’t already exist and apply any configured index templates. Defaults to true."
    name-zh: "如果索引不存在则自动创建，并应用所有已配置的索引模板。默认为true。"


placeholder:
  - name: "Please enter a custom quota, the unit is `Gi`"
    name-zh: "请输入自定义配额,单位为Gi"
  - name: "Please enter a custom quota, the unit is `Core`"
    name-zh: "请输入自定义配额,单位为Core"
  - name: "Please enter the storage size"
    name-zh: "请输入存储大小"
  - name: "Please select storage"
    name-zh: "请选择存储"
  - name: "Please enter Instances"
    name-zh: "请输入实例数"
  - name: "Enter your admin password"
    name-zh: "输入管理员账户密码"
  - name: "Please enter the number of instances"
    name-zh: "请输入端口号，点击回车进行添加"

label:
  - name: "AdminPassword"
    name-zh: "管理员账号密码"
  - name: "Memory"
    name-zh: "内存"
  - name: "Replicas"
    name-zh: "实例数"
  - name: "Version"
    name-zh: "版本"

  - name: "StorageSize"
    name-zh: "存储大小"

  - name: "StorageClass"
    name-zh: "存储类"
  - name: "Load Balancer Controller"
    name-zh: "负载均衡控制器名称"
  - name: "Load Balancer Address"
    name-zh: "负载均衡地址"
  - name: "Redis Node Port"
    name-zh: "Redis节点端口"
  - name: "Redis Bus Port"
    name-zh: "Redis总线端口"
  - name: "protocol"
    name-zh: "协议"
  - name: "Deployment Method"
    name-zh: "部署方式"
  - name: "Deployment"
    name-zh: "无状态部署"
  - name: "StatefulSet"
    name-zh: "有状态部署"




