mainVersionGroups:
  "6.x":
    - "6.8.22"
  "7.16.x":
    - "7.16.3"
    - "7.16.2"
  "7.17.x":
    - "7.17.28"
  "8.14.x":
    - "8.14.3"

crossUpgradeRules:
  "6.x":
    - "6.x"
  "7.16.x":
    - "7.16.x"
    - "7.17.x"
  "8.14.x":
    - "8.14.x"
crossDowngradeRules:
  "6.x": []
  "7.16.x": []
  "7.17.x": []
  "8.14.x": []