mainVersionGroups:
  "6.x":
    - "6.8.22"
  "7.x":
    - "7.16.3"
    - "7.16.2"
  "8.x":
    - "8.11.3"
    - "8.13.4"

crossUpgradeRules:
  "6.x":
    - "6.x"
  "7.x":
    - "7.x"
  "8.x":
    - "8.x"