elasticPassword: Hc@Cloud01
#encodePassword: SGNAQ2xvdWQwMQ==
args: {}

# 用户自定义的参数
additionArgs: {}

storage:
  masterSize: 5Gi
  dataSize: 5Gi
  clientSize: 5Gi
  coldSize: 5Gi
hostNetwork: false

# 默认使用es6.8.22版本; 目前支持版本 6.8.22; 7.16.2; 7.16.3; 8.11.3; 8.13.4
version: "7.16.3"

image:
  repository: harbor.middleware.com/middleware
  pullPolicy: IfNotPresent
  busyImageTag: "1.0"
  kibanaImageTag_6_8_10: 6.8.10
  kibanaImageTag_7_16_3: 7.16.3
  kibanaImageTag_7_16_2: 7.16.2
  kibanaImageTag_8_11_3: 8.11.3
  kibanaImageTag_8_13_4: 8.13.4
  initImageTag: "v1.7.0"
  elasticImageTag_6_8_22: 6.8.22-466e79
  elasticImageTag_7_16_3: 7.16.3-466e79
  elasticImageTag_7_16_2: 7.16.2-466e79
  elasticImageTag_8_11_3: 8.11.3-466e79
  elasticImageTag_8_13_4: 8.13.4-466e79
  exporterImageTag: v1.6.0
  testImageTag: v0.3

port:
  esExporterPort: 19114
  esHttpPort: 9200
  esKibanaPort: 5200
  esTcpPort: 9300

# 集群名称
clusterName: {}

# kibana 副本
kibanaReplicas: 1
cluster:
  mode: simple
  masterReplacesCount: 3

#  mode: complex
#  masterReplacesCount: 3
#  dataReplacesCount: 3
#  clientReplacesCount: 2
#  coldReplacesCount: 3


nameOverride: ""
fullnameOverride: ""

# Java 堆大小建议设置Pod 内存limit 的50%
#esJavaOpts:

resources:
  cold:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  client:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  data:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  kibana:
    limits:
      cpu: "500m"
      memory: 1Gi
    requests:
      cpu: "500m"
      memory: 1Gi
  master:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi

nodeSelector: {}

# 支持扩展statefulset.spec.template.spec
statefulSetConfiguration: {} 
#  tolerations:
#  - key: "example-key"
#    operator: "Exists"
#    effect: "NoSchedule"

exporterDeploymentConfiguration: {}
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: zone
#            operator: In
#            values:
#            - zoneA
#  tolerations:
#  - key: "harm.cn/system"
#    effect: "NoSchedule"
#  - key: "harm.cn/type"
#    value: "active-active"
#    effect: "NoSchedule"

kibanaDeploymentConfiguration: {}
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: zone
#            operator: In
#            values:
#            - zoneA
#  tolerations:
#  - key: "harm.cn/system"
#    effect: "NoSchedule"
#  - key: "harm.cn/type"
#    value: "active-active"
#    effect: "NoSchedule"


#设置nodeAffinity
nodeAffinity: {}
#  requiredDuringSchedulingIgnoredDuringExecution:
#    nodeSelectorTerms:
#      - matchExpressions:
#          - key: kubernetes.io/hostname
#            operator: In
#            values:
#            - slave-100

podAntiAffinityTopologKey: "kubernetes.io/hostname"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"

tolerations: []
#- key: "example-key"
#  operator: "Exists"
#  effect: "NoSchedule"

annotations: {}

labels: {}

extraVolumes: {}
#  name: elasticsearch-backup
#  persistentVolumeClaim:
#    claimName: elasticsearch-backup

extraVolumeMounts: {}
#  mountPath: /data-backup
#  name: elasticsearch-backup

#name规范为 节点类型+Node+'-'+定制目录功能，比如masterNode-data、masterNode-log、coldNode-data、clientNode-data
customVolumes: {}
#  - name: masterNode-data
#    mountPath: /es/data
#    targetContainers:
#      - es-cluster
#    storageClass: local-path
#    volumeSize: 1G
#    hostPath: /es/data
#  - name: masterNode-logs
#    mountPath: /es/logs
#    targetContainers:
#      - es-cluster
#    storageClass: local-path
#    volumeSize: 1G
#    hostPath: /es/logs
#  - name: dataNode-data
#    mountPath: /es/datanode_data
#    targetContainers:
#      - es-cluster
#    storageClass: local-path
#    volumeSize: 1G
#    hostPath: /es/datanode/data
#  - name: dataNode-logs
#    mountPath: /es/datanode_logs
#    targetContainers:
#      - es-cluster
#    storageClass: local-path
#    volumeSize: 1G
#    hostPath: /es/datanode/logs

activeActive:
  enable: false