apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: elasticsearch-checkhealth-config
spec:
  template: |
    apiVersion: v1
    data:
      checkHealth.sh: |
        #!/usr/bin/env bash
        statusCode="$(curl -I -o /dev/null -s -w '%{http_code}' \
          --connect-timeout {{ default 3 .Values.healthCheck.curlConnectTimeoutSeconds }} \
          --max-time {{ default 18 .Values.healthCheck.curlMaxTimeSeconds }} \
          -u elastic:{{ .Values.elasticPassword | quote }} \
          ${PODIP}:{{ .Values.port.esHttpPort }} || true)"
        if [[ "${statusCode}" == "503" || "${statusCode}" == "200" || "${statusCode}" == "401" ]];then
            exit 0
        else
            exit 1
        fi
    kind: ConfigMap
    metadata:
      labels:
        clusterName: {{ .Globe.Name }}
      name: {{ .Globe.Name }}-checkhealth-config
