apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: elasticsearch-clusterrolebinding
spec:
  template: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: {{ .Globe.Name }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole 
      name: {{ .Globe.Name }}
    subjects:
    - kind: ServiceAccount
      name: {{ .Globe.Name }}-job
      namespace: {{ .Globe.Namespace }}