apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: elasticsearch-connection-credential
spec:
  template: |
    apiVersion: v1
    stringData:
      endpoint: {{ .Globe.Name }}-master.{{ .Globe.Namespace }}.svc
      port: "9200"
      username: "elastic"
      {{- if .Values.encodePassword }}
      password: "{{ (b64dec .Values.encodePassword) | default .Values.elasticPassword }}"
      {{- else }}
      password: "{{ .Values.elasticPassword }}"
      {{- end }}
    kind: Secret
    metadata:
      name: {{ .Globe.Name }}-credential
      namespace: {{ .Globe.Namespace }}
    type: Opaque