apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: elasticsearch-serviceaccount-sa
spec:
  template: |
    {{- if eq .Values.activeActive.enable true}}
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ .Globe.Name }}-sa
    {{- end }}