apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: elasticsearch-restore
  annotations:
    alias: "Restore"
spec:
  baselineType: "NormalAction"
  actionType: "restore"
  necessary:
    annotations: '{"type":"string","label":"Additional Annotations (JSON map)","required":false,"visible": true}'
    labels: '{"type":"string","label":"Additional labels (JSON map)","required":false,"visible": true}'
    customRestores: {}
  steps:
    - name: create-restore
      type: "KubectlEdit"
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            name: "{{ .Globe.MiddlewareName }}"
            type: "escluster"
            customRestores: {{ toJson .Necessary.customRestores }}
          }
          resource: {
            apiversion: "harmonycloud.cn/v1"
            kind: "MiddlewareRestore"
            name: "{{ .Globe.MiddlewareName }}-restore-{{ now | date `20060102150405` }}"
            namespace: "{{ .Globe.Namespace }}"
            annotations: {
              "middlewarebackup.job.mode": "snapshot"
              {{- range $k, $v := .Necessary.annotations }}
              {{ printf "%q" $k }}: {{ printf "%q" $v }}
              {{- end }}
            }
            labels: {
              {{- range $k, $v := .Necessary.labels }}
              {{ printf "%q" $k }}: {{ printf "%q" $v }}
              {{- end }}
            }
          }
        }
