apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: elasticsearch-cluster
  annotations:
    OperationType: Create
    developerPass: es
    mode: "HA"
    baselineName: "Cluster Mode"
    description: "Cluster Mode Baseline, incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
spec:
  operatorBaseline:
    name: elasticsearch-operator-standard
    gvkName: v1alpha1
  necessary:
    version: '{"type":"version","label":"Version","required":true,"default":"7.17.28"}'
    repository: ""
    password: |
      {
        "type": "password",
        "label": "AdminPassword",
        "required": true,
        "description": "Please enter a password consisting of English letters, numbers, or the special characters \"~, _, .\"",
        "placeholder": "Enter your admin password",
        "pattern": "^[A-Za-z0-9~_.]*$"
       }
    #    elasticsearchPort:
    #      exporter: "19114"
    #      http: "9200"
    #      kibana: "5200"
    #      tcp: "9300"
    resource:
      master:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1","min":"0.1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4","min":"0.1"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1","min":"0.1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4","min":"0.1"}'
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"Nodes,It is recommended to have at least 3 to ensure high availability.","default":3,"pattern":"^[3-9]\\d*$","placeholder":"Please enter Instances","min":"3"}'
        volume:
          size: '{"type":"int","label":"StorageSize","required":true,"pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","placeholder":"Please enter the storage size","min":"0.1"}'
          storageClass: '{"type":"storageClass","label":"StorageClass","required":true,"description":"Please select storage","placeholder":"Please enter Instances"}'
  preActions:
    - name: pre-elasticsearch-heimdallr-hdpool
      parameters:
        networkCardList: [ ]
        annotations: { }
      fixed: false
      exposed: true
    - name: pre-elasticsearch-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-elasticsearch-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      exposed: true
    - name: pre-elasticsearch-tolerations
      parameters:
        tolerations: []
      exposed: true
    - name: pre-elasticsearch-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: {}
        activeActive: false
      exposed: true
  #    - name: pre-elasticsearch-kibana-tolerations
  #      parameters:
  #        tolerations: []
  #      exposed: true
  #    - name: pre-elasticsearch-kibana-affinity
  #      parameters:
  #        nodeAffinity: {}
  #      exposed: true
  #    - name: pre-elasticsearch-exporter-tolerations
  #      parameters:
  #        tolerations: []
  #      exposed: true
  #    - name: pre-elasticsearch-exporter-affinity
  #      parameters:
  #        nodeAffinity: {}
  #      exposed: true
  parameters:
    clusterMode: simple
    clusterName: "{{ .Globe.Name }}"
    checkHealthConfigMap: "{{ .Globe.Name }}-checkhealth-config"
    elasticKibanaConfigMap: "{{ .Globe.Name }}-kibana-config"
    elasticSearchConfigMap: "{{ .Globe.Name }}-es-config"
    esExporterPort: 19114
    esHttpPort: 9200
    esKibanaPort: 5200
    esTcpPort: 9300
    elasticPass: '"{{ .Necessary.password }}"'
    kibanaImage: '{{ .Necessary.repository }}/kibana:{{ if contains "6.8" .Necessary.version }}6.8.10{{ else if eq "7.16.2" .Necessary.version }}7.16.2{{ else if eq "7.16.3" .Necessary.version }}7.16.3{{ else if eq "7.17.28" .Necessary.version }}7.17.28{{ else if eq "8.11.3" .Necessary.version }}8.11.3{{ else }}8.13.4{{ end }}'
    elasticBusyImage: "{{ .Necessary.repository }}/busybox:1.0"
    kibanaReplicas: 1
    masterReplaces: "{{ .Necessary.resource.master.replicas }}"
    dataReplaces:
    clientReplaces:
    coldReplaces:
    totalReplaces: "{{ .Necessary.resource.master.replicas }}"
    pod:
      - env:
          - name: PathRepo
            value: /data/elastic/{ClusterName}/{PodName}/data/data_back
        initImage: "{{ .Necessary.repository }}/es-init:v1.7.0"
        podAntiAffinityTopologKey: kubernetes.io/hostname
        podAntiAffinity: soft
        storage:
          dataSize: 5Gi
          clientSize: 5Gi
          coldSize: 5Gi
          masterSize: "{{ .Necessary.resource.master.volume.size }}"
          masterClass: "{{ .Necessary.resource.master.volume.storageClass }}"
        middlewareImage: '{{ .Necessary.repository }}/elastic:{{ if contains "6.8" .Necessary.version }}6.8.22-466e79{{ else if eq "7.16.2" .Necessary.version }}7.16.2-466e79{{ else if eq "7.16.3" .Necessary.version }}7.16.3-466e79{{ else if eq "7.17.28" .Necessary.version }}7.17.28{{ else if eq "8.11.3" .Necessary.version }}8.11.3-466e79{{ else }}8.13.4-751e{{ end }}'
        monitorImage: "{{ .Necessary.repository }}/es-exporter:v1.6.0"
        hostNetwork: false
        resources:
          cold:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
          client:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
          data:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
          kibana:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 1Gi
          master:
            limits:
              cpu: '"{{ .Necessary.resource.master.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.master.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.master.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.master.requests.memory }}"'
        updateStrategy: {}
    projectId: a9927d1581674f27
    repository: "{{ .Necessary.repository }}"
    type: simple
    updateStrategy: {}
    version: '{{ if contains "6.8" .Necessary.version }}6.8.22{{ else if eq "7.16.2" .Necessary.version }}7.16.2{{ else if eq "7.16.3" .Necessary.version }}7.16.3{{ else if eq "7.17.28" .Necessary.version }}7.17.28{{ else }}8.11.3{{ end }}'
    esMaster:
    esData:
    esCold:
    esClient:
    statefulset:
      spec:
        updateStrategy:
          type: RollingUpdate
        template:
          metadata:
          spec:
            initContainers:
              - env:
                  - name: NodeName
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: spec.nodeName
                name: "{{ .Globe.Name }}-init"
    deploymentComponent:
      kibana:
        spec:
          template:
            metadata:
            spec:
      exporter:
        spec:
          template:
            metadata:
            spec:
    volumeClaimTemplates:
      - metadata:
          creationTimestamp: null
          name: es-data
        spec:
          accessModes:
            - ReadWriteOnce
          dataSource: null
          resources:
            requests:
              storage: "0"
        status: {}
    volumes: {}
  configurations:
    - name: elasticsearch-alertrule
      values: {}
    - name: elasticsearch-clusterrole
      values: {}
    - name: elasticsearch-clusterrolebinding
      values: {}
    - name: elasticsearch-clusterrolebinding-sa
      values:
        activeActive:
          enable: false
    - name: elasticsearch-serviceaccount
      values: {}
    - name: elasticsearch-serviceaccount-sa
      values:
        activeActive:
          enable: false
    - name: elasticsearch-connection-credential
      values:
        elasticPassword: '"{{ .Parameters.elasticPass }}"'
    - name: elasticsearch-checkhealth-config
      values:
        elasticPassword: '"{{ .Parameters.elasticPass }}"'
        port:
          esHttpPort: "{{ .Parameters.esHttpPort }}"
    - name: elasticsearch-es-config
      values:
        args: {}
        version: "{{ .Parameters.version }}"
        port:
          esHttpPort: "{{ .Parameters.esHttpPort }}"
          esTcpPort: "{{ .Parameters.esTcpPort }}"
        additionArgs: {}
    - name: elasticsearch-kibana-config
      values:
        port:
          esKibanaPort: "{{ .Parameters.esKibanaPort }}"
        version: "{{ .Parameters.version }}"
        elasticPassword: '"{{ .Parameters.elasticPass }}"'
    - name: elasticsearch-servicemonitor
      values: {}
