apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: elasticsearch-complex-cluster-active
  annotations:
    OperationType: Create
    developerPass: es
    baselineName: "混合模式-双活"
    description: "混合模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
    active: "3"
spec:
  operatorBaseline:
    name: elasticsearch-operator-standard
    gvkName: v1alpha1
  necessary:
    version: '{"type":"version","label":"Version","required":true,"default":"7.17.28"}'
    repository: ""
    password: |
      {
        "type": "password",
        "label": "AdminPassword",
        "required": true,
        "description": "Please enter a password consisting of English letters, numbers, or special characters ~, _, .",
        "placeholder": "Enter your admin password",
        "pattern": "^[A-Za-z0-9~_.]*$"
       }
    # elasticsearchPort:
    #   exporter: "19114"
    #   http: "9200"
    #   kibana: "5200"
    #   tcp: "9300"
    resource:
      client:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"client节点数量，请输入2或2以上的偶数","default":2,"pattern":"^(?:[2468]|[1-9]\\d*[02468])$","placeholder":"Please enter Instances"}'
        volumes: ""
      cold:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"Number of cold nodes, please enter an even number greater than or equal to 2","default":2,"pattern":"^(?:[2468]|[1-9]\\d*[02468])$","placeholder":"Please enter Instances"}'
        volumes: ""
      data:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"Number of data nodes, please enter an even number greater than or equal to 4","default":4,"pattern":"^(?:[468]|[1-9]\\d*[02468])$","placeholder":"Please enter Instances"}'
        volumes: ""
      kibana:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"0.5"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"1"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"0.5"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"1"}'
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"The minimum value for kibana count is 1","default":1,"pattern":"^[1-9]\\d*$","placeholder":"Please enter Instances"}'
      master:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"Number of master nodes, please enter an odd number greater than or equal to 3","default":3,"pattern":"^(3|5|7|9|[1-9]\\d*[13579])$","placeholder":"Please enter Instances"}'
        volumes: ""
  preActions:
    - name: pre-elasticsearch-heimdallr-hdpool
      parameters:
        networkCardList: [ ]
        annotations: { }
      fixed: false
      exposed: true
    - name: pre-elasticsearch-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-elasticsearch-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      exposed: true
    - name: pre-elasticsearch-tolerations
      parameters:
        tolerations: [ ]
      exposed: true
    - name: pre-elasticsearch-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: { }
        activeActive: true
      exposed: true
    # - name: pre-elasticsearch-kibana-affinity
    #   parameters:
    #     nodeAffinity: { }
    #   exposed: true
    # - name: pre-elasticsearch-exporter-tolerations
    #   parameters:
    #     tolerations: [ ]
    #   exposed: true
    # - name: pre-elasticsearch-exporter-affinity
    #   parameters:
    #     nodeAffinity: { }
    #   exposed: true
    # - name: pre-elasticsearch-kibana-tolerations
    #   parameters:
    #     tolerations: [ ]
    #   exposed: true
  parameters:
    clusterMode: complex
    clusterName: "{{ .Globe.Name }}"
    checkHealthConfigMap: "{{ .Globe.Name }}-checkhealth-config"
    elasticKibanaConfigMap: "{{ .Globe.Name }}-kibana-config"
    elasticSearchConfigMap: "{{ .Globe.Name }}-es-config"
    esExporterPort: 19114
    esHttpPort: 9200
    esKibanaPort: 5200
    esTcpPort: 9300
    elasticPass: '"{{ .Necessary.password }}"'
    kibanaImage: '{{ .Necessary.repository }}/kibana:{{ if contains "6.8" .Necessary.version }}6.8.10{{ else if eq "7.16.2" .Necessary.version }}7.16.2{{ else if eq "7.16.3" .Necessary.version }}7.16.3{{ else if eq "7.17.28" .Necessary.version }}7.17.28{{ else if eq "8.11.3" .Necessary.version }}8.11.3{{ else }}8.13.4{{ end }}'
    elasticBusyImage: "{{ .Necessary.repository }}/busybox:1.0"
    kibanaReplicas: "{{ .Necessary.resource.kibana.replicas }}"
    masterReplaces: "{{ .Necessary.resource.master.replicas }}"
    dataReplaces: "{{ .Necessary.resource.data.replicas }}"
    clientReplaces: "{{ .Necessary.resource.client.replicas }}"
    coldReplaces: "{{ .Necessary.resource.cold.replicas }}"
    totalReplaces: "{{ add .Necessary.resource.master.replicas .Necessary.resource.data.replicas .Necessary.resource.client.replicas .Necessary.resource.cold.replicas }}"
    pod:
      - env:
          - name: PathRepo
            value: /data/elastic/{ClusterName}/{PodName}/data/data_back
        initImage: "{{ .Necessary.repository }}/es-init:v1.7.0"
        podAntiAffinityTopologKey: kubernetes.io/hostname
        podAntiAffinity: soft
        storage:
          clientSize: '{{ index .Necessary.resource.client.volumes 0 "size" }}'
          coldSize: '{{ index .Necessary.resource.cold.volumes 0 "size" }}'
          dataSize: '{{ index .Necessary.resource.data.volumes 0 "size" }}'
          masterSize: '{{ index .Necessary.resource.master.volumes 0 "size" }}'
          clientClass: '{{ range $i, $v := .Necessary.resource.client.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
          coldClass: '{{ range $i, $v := .Necessary.resource.cold.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
          dataClass: '{{ range $i, $v := .Necessary.resource.data.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
          masterClass: '{{ range $i, $v := .Necessary.resource.master.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
        middlewareImage: '{{ .Necessary.repository }}/elastic:{{ if contains "6.8" .Necessary.version }}6.8.22-466e79{{ else if eq "7.16.2" .Necessary.version }}7.16.2-466e79{{ else if eq "7.16.3" .Necessary.version }}7.16.3-466e79{{ else if eq "7.17.28" .Necessary.version }}7.17.28{{ else if eq "8.11.3" .Necessary.version }}8.11.3-466e79{{ else }}8.13.4-751e{{ end }}'
        monitorImage: "{{ .Necessary.repository }}/es-exporter:v1.6.0"
        hostNetwork: false
        resources:
          client:
            limits:
              cpu: '"{{ .Necessary.resource.client.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.client.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.client.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.client.requests.memory }}"'
          cold:
            limits:
              cpu: '"{{ .Necessary.resource.cold.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.cold.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.cold.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.cold.requests.memory }}"'
          data:
            limits:
              cpu: '"{{ .Necessary.resource.data.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.data.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.data.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.data.requests.memory }}"'
          kibana:
            limits:
              cpu: '"{{ .Necessary.resource.kibana.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.kibana.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.kibana.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.kibana.requests.memory }}"'
          master:
            limits:
              cpu: '"{{ .Necessary.resource.master.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.master.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.master.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.master.requests.memory }}"'
    projectId: a9927d1581674f27
    repository: "{{ .Necessary.repository }}"
    type: complex
    updateStrategy: { }
    version: '{{ if contains "6.8" .Necessary.version }}6.8.22{{ else if eq "7.16.2" .Necessary.version }}7.16.2{{ else if eq "7.16.3" .Necessary.version }}7.16.3{{ else if eq "7.17.28" .Necessary.version }}7.17.28{{ else }}8.11.3{{ end }}'
    esMaster:
    esData:
    esCold:
    esClient:
    statefulset:
      spec:
        updateStrategy:
          type: RollingUpdate
        template:
          metadata:
          spec:
            initContainers:
              - env:
                  - name: NodeName
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: spec.nodeName
                  - name: ActiveActive
                    value: "true"
                name: "{{ .Globe.Name }}-init"
            serviceAccountName: "{{ .Globe.Name }}-sa"
    deploymentComponent:
      kibana:
        spec:
          template:
            metadata:
            spec:
      exporter:
        spec:
          template:
            metadata:
            spec:
    volumeClaimTemplates:
      - metadata:
          creationTimestamp: null
          name: es-data
        spec:
          accessModes:
            - ReadWriteOnce
          dataSource: null
          resources:
            requests:
              storage: "0"
    volumes: { }
  configurations:
    - name: elasticsearch-alertrule
      values: { }
    - name: elasticsearch-clusterrole
      values: { }
    - name: elasticsearch-clusterrolebinding
      values: { }
    - name: elasticsearch-clusterrolebinding-sa
      values:
        activeActive:
          enable: true
    - name: elasticsearch-serviceaccount
      values: { }
    - name: elasticsearch-serviceaccount-sa
      values:
        activeActive:
          enable: true
    - name: elasticsearch-connection-credential
      values:
        elasticPassword: '"{{ .Parameters.elasticPass }}"'
    - name: elasticsearch-checkhealth-config
      values:
        elasticPassword: '"{{ .Parameters.elasticPass }}"'
        port:
          esHttpPort: "{{ .Parameters.esHttpPort }}"
    - name: elasticsearch-es-config
      values:
        args: { }
        version: "{{ .Parameters.version }}"
        port:
          esHttpPort: "{{ .Parameters.esHttpPort }}"
          esTcpPort: "{{ .Parameters.esTcpPort }}"
        additionArgs: { }
    - name: elasticsearch-kibana-config
      values:
        port:
          esKibanaPort: "{{ .Parameters.esKibanaPort }}"
        version: "{{ .Parameters.version }}"
        elasticPassword: '"{{ .Parameters.elasticPass }}"'
    - name: elasticsearch-servicemonitor
      values: { }
