apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: elasticsearch-complex-cluster-active
  annotations:
    OperationType: Create
    developerPass: es
    baselineName: "混合模式"
    description: "混合模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
    active: "3"
spec:
  operatorBaseline:
    name: elasticsearch-operator-standard
    gvkName: v1alpha1
  necessary:
    version: '{"type":"version","label":"版本","required":true,"default":"7.16.3"}'
    repository: ""
    password: '{"type":"password","label":"管理员账号密码","required":true,"description":"MySQL 管理员的初始密码，需包含大小写字母、数字和特殊字符","pattern":"^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$","placeholder":"输入管理员账户密码","default":"Hc@Cloud01"}'
    # elasticsearchPort:
    #   exporter: "19114"
    #   http: "9200"
    #   kibana: "5200"
    #   tcp: "9300"
    resource:
      client:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"client节点数量，建议至少2个以保证高可用","default":2,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volumes: ""
      cold:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"cold节点数量，建议至少2个以保证高可用","default":3,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volumes: ""
      data:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"data节点数量，建议至少2个以保证高可用","default":3,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volumes: ""
      kibana:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"0.5"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"1"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"0.5"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"1"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"kibana节点数量","default":1,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
      master:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"master节点数量","default":3,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volumes: ""
  preActions:
    - name: pre-elasticsearch-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-elasticsearch-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      exposed: true
    - name: pre-elasticsearch-tolerations
      parameters:
        tolerations: [ ]
      exposed: true
    - name: pre-elasticsearch-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: { }
        activeActive: true
      exposed: true
    # - name: pre-elasticsearch-kibana-affinity
    #   parameters:
    #     nodeAffinity: { }
    #   exposed: true
    # - name: pre-elasticsearch-exporter-tolerations
    #   parameters:
    #     tolerations: [ ]
    #   exposed: true
    # - name: pre-elasticsearch-exporter-affinity
    #   parameters:
    #     nodeAffinity: { }
    #   exposed: true
    # - name: pre-elasticsearch-kibana-tolerations
    #   parameters:
    #     tolerations: [ ]
    #   exposed: true
  parameters:
    clusterMode: complex
    clusterName: "{{ .Globe.Name }}"
    checkHealthConfigMap: "{{ .Globe.Name }}-checkhealth-config"
    elasticKibanaConfigMap: "{{ .Globe.Name }}-kibana-config"
    elasticSearchConfigMap: "{{ .Globe.Name }}-es-config"
    esExporterPort: 19114
    esHttpPort: 9200
    esKibanaPort: 5200
    esTcpPort: 9300
    elasticPass: "{{ .Necessary.password }}"
    kibanaImage: "{{ .Necessary.repository }}/kibana:7.16.3"
    elasticBusyImage: "{{ .Necessary.repository }}/busybox:1.0"
    kibanaReplicas: "{{ .Necessary.resource.kibana.replicas }}"
    masterReplaces: "{{ .Necessary.resource.master.replicas }}"
    dataReplaces: "{{ .Necessary.resource.data.replicas }}"
    clientReplaces: "{{ .Necessary.resource.client.replicas }}"
    coldReplaces: "{{ .Necessary.resource.cold.replicas }}"
    totalReplaces: "{{ add .Necessary.resource.master.replicas .Necessary.resource.data.replicas .Necessary.resource.client.replicas .Necessary.resource.cold.replicas }}"
    pod:
      - env:
          - name: PathRepo
            value: /data/elastic/{ClusterName}/{PodName}/data/data_back
        initImage: "{{ .Necessary.repository }}/es-init:v1.7.0"
        podAntiAffinityTopologKey: kubernetes.io/hostname
        podAntiAffinity: soft
        storage:
          clientSize: '{{ index .Necessary.resource.client.volumes 0 "size" }}'
          coldSize: '{{ index .Necessary.resource.cold.volumes 0 "size" }}'
          dataSize: '{{ index .Necessary.resource.data.volumes 0 "size" }}'
          masterSize: '{{ index .Necessary.resource.master.volumes 0 "size" }}'
          clientClass: '{{ range $i, $v := .Necessary.resource.client.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
          coldClass: '{{ range $i, $v := .Necessary.resource.cold.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
          dataClass: '{{ range $i, $v := .Necessary.resource.data.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
          masterClass: '{{ range $i, $v := .Necessary.resource.master.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
        middlewareImage: "{{ .Necessary.repository }}/elastic:7.16.3-466e79"
        monitorImage: "{{ .Necessary.repository }}/es-exporter:v1.6.0"
        hostNetwork: false
        resources:
          client:
            limits:
              cpu: '"{{ .Necessary.resource.client.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.client.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.client.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.client.requests.memory }}"'
          cold:
            limits:
              cpu: '"{{ .Necessary.resource.cold.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.cold.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.cold.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.cold.requests.memory }}"'
          data:
            limits:
              cpu: '"{{ .Necessary.resource.data.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.data.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.data.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.data.requests.memory }}"'
          kibana:
            limits:
              cpu: '"{{ .Necessary.resource.kibana.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.kibana.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.kibana.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.kibana.requests.memory }}"'
          master:
            limits:
              cpu: '"{{ .Necessary.resource.master.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.master.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.master.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.master.requests.memory }}"'
    projectId: a9927d1581674f27
    repository: "{{ .Necessary.repository }}"
    type: complex
    updateStrategy: { }
    version: "7.16.3"
    esMaster:
    esData:
    esCold:
    esClient:
    statefulset:
      spec:
        updateStrategy:
          type: RollingUpdate
        template:
          metadata:
          spec:
            initContainers:
              - env:
                  - name: NodeName
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: spec.nodeName
                  - name: ActiveActive
                    value: "true"
                name: "{{ .Globe.Name }}-init"
            serviceAccountName: "{{ .Globe.Name }}-sa"
    deploymentComponent:
      kibana:
        spec:
          template:
            metadata:
            spec:
      exporter:
        spec:
          template:
            metadata:
            spec:
    volumeClaimTemplates:
      - metadata:
          creationTimestamp: null
          name: es-data
        spec:
          accessModes:
            - ReadWriteOnce
          dataSource: null
          resources:
            requests:
              storage: "0"
    volumes: { }
  configurations:
    - name: elasticsearch-alertrule
      values: { }
    - name: elasticsearch-clusterrole
      values: { }
    - name: elasticsearch-clusterrolebinding
      values: { }
    - name: elasticsearch-clusterrolebinding-sa
      values:
        activeActive:
          enable: true
    - name: elasticsearch-serviceaccount
      values: { }
    - name: elasticsearch-serviceaccount-sa
      values:
        activeActive:
          enable: true
    - name: elasticsearch-connection-credential
      values:
        elasticPassword: "{{ .Parameters.elasticPass }}"
    - name: elasticsearch-checkhealth-config
      values:
        elasticPassword: "{{ .Parameters.elasticPass }}"
        port:
          esHttpPort: "{{ .Parameters.esHttpPort }}"
    - name: elasticsearch-es-config
      values:
        args: { }
        version: "{{ .Parameters.version }}"
        port:
          esHttpPort: "{{ .Parameters.esHttpPort }}"
          esTcpPort: "{{ .Parameters.esTcpPort }}"
        additionArgs: { }
    - name: elasticsearch-kibana-config
      values:
        port:
          esKibanaPort: "{{ .Parameters.esKibanaPort }}"
        version: "{{ .Parameters.version }}"
        elasticPassword: "{{ .Parameters.elasticPass }}"
    - name: elasticsearch-servicemonitor
      values: { }
